# Generated by Django 5.0.2 on 2024-06-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
    ]
